# Generated by Django 2.0.2 on 2018-07-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=48)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('submit', models.IntegerField(blank=True, null=True)),
                ('solved', models.IntegerField(blank=True, null=True)),
                ('defunct', models.CharField(max_length=1)),
                ('ip', models.CharField(max_length=20)),
                ('accesstime', models.DateTimeField(blank=True, null=True)),
                ('volume', models.IntegerField()),
                ('language', models.IntegerField()),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('reg_time', models.DateTimeField(blank=True, null=True)),
                ('nick', models.CharField(max_length=100)),
                ('signature', models.TextField(blank=True, null=True)),
                ('school', models.CharField(max_length=100)),
                ('identity', models.CharField(max_length=1)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('qq', models.CharField(blank=True, max_length=20, null=True)),
                ('academy', models.IntegerField(blank=True, null=True)),
                ('major', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('cookie', models.CharField(blank=True, max_length=32, null=True)),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('class_id', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('avatarurl', models.CharField(blank=True, db_column='avatarUrl', max_length=500, null=True)),
                ('last_submit', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'users',
            },
        ),
    ]
